# Site settings
title: Designer Portfolio
email: mark@thetechguysblog.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specialising in Jekyll,
  HTML, CSS and Javascript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: markmushiva
github_username:  Highfather87
google_username: markmushiva

permalink: /:categories/:title

#Links array we create to hold our link values
links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me


# Build settings
markdown: kramdown
